## GLM for predicting price

In [13]:
import numpy as np
import pandas as pd
import random
from patsy import dmatrices
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.impute import SimpleImputer
from tqdm.notebook import tqdm
import statsmodels.api as sm

In [25]:
X = pd.read_json('../data/model_data/X.json')
y = pd.read_json('../data/model_data/y.json', typ='series')
data = pd.concat([np.exp(y).rename('log(price)'), X], axis=1)
data

,log(price),bed,bath,area,laundry,pets,parking,lat,lon,distance_to_CCTC,distance_to_Pierpont,distance_to_Stadium,distance_to_Union,distance_to_Ross,distance_to_IM,distance_to_NCRB,distance_to_CCRB,distance_to_UgLi,neighborhood,property_type
0,1095.0,0.2,0.111111,0.102953,1.0,1.0,1.0,0.277344,0.556060,0.225814,0.259883,0.186173,0.222507,0.227654,0.211189,0.279171,0.243785,0.217891,Other Surrounding Areas,apartment
1,2000.0,0.4,0.277778,0.235204,1.0,1.0,1.0,0.372139,0.512543,0.082072,0.152201,0.034829,0.066600,0.074705,0.058171,0.174699,0.103561,0.068031,Other Surrounding Areas,house
2,1385.0,0.1,0.111111,0.094011,1.0,1.0,1.0,0.498713,0.633849,0.226808,0.112882,0.305859,0.262403,0.238672,0.304066,0.099647,0.219609,0.244499,Other Surrounding Areas,apartment
3,1185.0,0.1,0.111111,0.094011,1.0,1.0,1.0,0.498713,0.633849,0.226808,0.112882,0.305859,0.262403,0.238672,0.304066,0.099647,0.219609,0.244499,Other Surrounding Areas,apartment
4,1375.0,0.1,0.111111,0.094011,1.0,1.0,0.0,0.498713,0.633849,0.226808,0.112882,0.305859,0.262403,0.238672,0.304066,0.099647,0.219609,0.244499,Other Surrounding Areas,apartment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5653,662.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5654,800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5655,800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5656,800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5657,800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## some data cleaning

In [15]:
# # one-hot-encode categorical features
# X_encoded = pd.get_dummies(X.select_dtypes(exclude=np.number))
# X_encoded
# X_float = X.select_dtypes(include=np.number)
# X = pd.concat([X_float, X_encoded], axis=1)
# col = X.columns.to_numpy()

In [16]:
# impute np.nan values with numerical sentinel 
imp = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value = -999)
X = imp.fit_transform(X)

In [17]:
# X_tr, X_test, y_tr, y_test = train_test_split(X, y, random_state=4)

In [18]:
# oops -- impute the few 0 values by mean imputation
y_test[y_test == 0] = np.mean(y_test)

## now for the model!

In [24]:
y, X = dmatrices('np.log(price) ~ Neighborhood + Wealth + Region', data=df, return_type='dataframe')

AttributeError: 'DataFrame' object has no attribute 'exog'